### ISSUE TITLE
Issue with debuff removal

### ISSUE THREAD

**Issue by Flecked42** [MarcelineVQ/Decursive#5]
Left clicking to remove debuffs doesn't seem to work like in the original mod.

**Comment by shikulja** [comment]
same, binded button and clicking not work, the problem with autoselfcast?

**Comment by MarcelineVQ** [comment]
Really strange, not sure what could be causing that at all

**Comment by Flecked42** [comment]
Seems to be working now, closing.

**Comment by MarcelineVQ** [comment]
I actually had this issue myself just recently but I have no idea why and
it wouldn't happen when I tried to reproduce it :(
